export const GET_POSTED_JOBS = 'GET_POSTED_JOBS';
export const POSTED_JOBS_SUCCESS = 'POSTED_JOBS_SUCCESS';
export const POSTED_JOBS_FAILED = 'POSTED_JOBS_FAILED';

export const GET_JOBS = 'GET_JOBS';
export const JOBS_SUCCESS = 'JOBS_SUCCESS';
export const JOBS_FAILED = 'JOBS_FAILED';

export const APPLY_JOB = 'APPLY_JOB';
export const APPLY_JOB_SUCCESS = 'APPLY_JOB_SUCCESS';
export const APPLY_JOB_FAILED = 'APPLY_JOB_FAILED';

export const GET_APPLICANTS = 'GET_APPLICANTS';
export const APPLICANTS_SUCCESS = 'APPLICANTS_SUCCESS';
export const APPLICANTS_FAILED = 'APPLICANTS_FAILED';
